config/routes.rb
Haedron::Application.routes.draw do
  get "home/index"
  get "system/index"

  devise_for :users

  resources :accounts
  resources :users, :except => 'show'

  match 'system/' => 'system#index', :as => :system

   root :to => "home#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  # Brazilian Rails
  usar_como_cnpj :legal_number
  
  # Validações
  validates_presence_of :display_name
  validates_length_of :display_name, :in => 4..45, :unless => :display_name_is_blank?
  validates_length_of :legal_name, :in => 4..60
  
  # Manager stub for future sake
  def manager
    "Lucas Castro"
  end

  # Creator stub for future sake
  def creator
    "Lucas Castro"
  end
  
  # My own set of Inherited Resources Views rules
  def form_attributes
    [:display_name, :legal_name, :legal_number]  
  end
    
  def main_attribute
    :display_name
  end
  
  def collection_attributes
    [ :legal_number, :manager]
  end
  
  def show_hintable_attributes
    [
      [:created_at, 'Criado em'],
      [:creator, 'Criado por'],
      [:manager, 'Gerenciado por'],
    ]
  end
  
  def show_upper_attributes
    [:legal_name, :legal_number]
  end  
  
  protected
  
  def legal_name_is_blank?
    self.legal_name.blank?
  end

  def display_name_is_blank?
    self.display_name.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable, :confirmable, :recoverable, :registerable and :activatable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  
  # avoid last user deletion
  before_destroy { |record| return false if User.count < 2  }
  
  def main_attribute
    :email
  end
  
  def form_attributes
    [:email, :password]  
  end

  def collection_attributes
    [ ]
  end
  
  def show_hintable_attributes
    [ ]
  end  
  
  def excluded_attributes
    [
      'encrypted_password',
      'password_salt',
      'reset_password_token',
      'remember_token',
      'remember_created_at',
      'sign_in_count',
      'current_sign_in_at',
      'last_sign_in_at',
      'current_sign_in_ip',
      'last_sign_in_ip',
    ]
  end
  
  def is_simple_object?
    true
  end
  
end

app/controllers/accounts_controller.rb
class AccountsController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_user!
  layout :specify_layout

  protected 

    def specify_layout
      controller_name == 'sessions' ? 'login' : 'application' 
    end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/system_controller.rb
class SystemController < ApplicationController
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  def update
    update! do |success, failure|
      success.html { redirect_to users_url }
    end
  end

  def create
    create! do |success, failure|
      success.html { redirect_to users_url }
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/system_helper.rb
module SystemHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inherited_resources/_collection_table.html.erb
<% excluded_attributes = ['id', 'created_at', 'updated_at'] %>
<% excluded_attributes << collection.first.main_attribute.to_s if collection.first.respond_to? :main_attribute %>

<% collection.each do |r| %>
<div class="list_item">

	<div class="item_main">
	    <% if r.respond_to? :main_attribute %>
		<div id="main_attribute">
			<% if r.respond_to? :is_simple_object? and r.is_simple_object? %>
	          <p><strong><%= r.send(r.main_attribute)%></strong></p>
			<% else  %>
	          <p><strong><%= link_to r.send(r.main_attribute), r %></strong></p>
			<% end %>
		</div>
		<% end %>

		<% if r.respond_to? :collection_attributes %>
		  <% r.collection_attributes.each do |attr| %>
              <p><%= r.send attr %></strong></p>
		  <% end %>
		<% else %>
		  <% sample_attributes = r.attributes %>
		  <% sample_attributes.delete "created_at" %>
		  <% sample_attributes.delete "updated_at" %>
		  <% sample_attributes.delete "id" %>
		  <% sample_attributes.delete collection.first.main_attribute.to_s if collection.first.respond_to? :main_attribute %>		
		  <% sample_attributes.size.times do %>
	        <p> <%= sample_attributes.shift[1] %></p>
		  <% end %>
		<% end %>
    </div>

	<div class="item_control">
    <p><%= link_to 'Alterar', edit_resource_url(r) %></p>
    <p><%= link_to 'Remover', r, :confirm => 'Tem certeza?', :method => :delete %></p>
	</div>
	<br class="clear" />
</div>
<% end %>

app/views/inherited_resources/_edit_navigation.html.erb
<p><%= link_to "Voltar", collection_url %></p>

app/views/inherited_resources/_form.html.erb
<%- simple_form_for("#{resource_instance_name.to_s.downcase}",
      resource,
      :url => resource.new_record? ? collection_url : resource_url(resource),
      :html => { :method => (resource.new_record? ? "post" : "put") }) do |f| %>
    <% if resource.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(resource.errors.count, "erro") %></p>

      <ul>
	  <% resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% if resource.respond_to? :form_attributes %>
    <% resource.form_attributes.each do |attr| %>
      <%= f.input attr, :label => false %>
    <% end %>
  <% else %>
    <% resource.attributes.each_pair do |field, value| %>
      <% next if ['id', 'created_at', 'updated_at'].include?(field) %>
      <%= f.input field.to_sym, :label => false %>
    <% end %>
  <% end %>
  <%= f.submit "Enviar" %>
<% end %>

app/views/inherited_resources/_index_navigation.html.erb
<div id="submenu">
	<ul>
		<% if collection.count > 0 %>
		<li><%= link_to '(+) Adicionar '+collection.first.class.human_name.titleize, new_resource_path %></li>
		<% else %>
		<li><%= link_to '(+) Adicionar', new_resource_path %></li>
		<% end %>
	</ul>
</div>

app/views/inherited_resources/_new_navigation.html.erb
<p><%= link_to "Voltar", collection_url %></p>

app/views/inherited_resources/_resource_detail.html.erb
<p id="notice"><%= notice %></p>

<div class="main_box">

    <% excluded_attributes = ['id', 'created_at', 'updated_at'] %>
    <% excluded_attributes += resource.excluded_attributes if resource.respond_to? :excluded_attributes %>
    <% excluded_attributes << resource.main_attribute.to_s if resource.respond_to? :main_attribute %>
    <% excluded_attributes.concat resource.show_upper_attributes.collect {|x| x.to_s } if resource.respond_to? :show_upper_attributes %>


	<div id="upper_attributes">
    <% if resource.respond_to? :show_upper_attributes %>
      <% resource.show_upper_attributes.each do |attr| %>
    	  <p><%= resource.send attr %></p>
	  <% end %>
	<% end %>
	</div>

    <% if resource.respond_to? :main_attribute %>
	<div id="main_attribute">
      <p class="big_text"><%= resource.send resource.main_attribute %></p>
	</div>
	<% end %>

	<% resource.attributes.each_pair do |attr, value| %>
        <% next if excluded_attributes.include?(attr) %>
        <p> <%= value %></p>
    <% end %>

    <% if resource.respond_to? :show_hintable_attributes %>
	<div id="hintable_attributes">
      <% resource.show_hintable_attributes.each do |attr_hint| %>
    	  <p><%= attr_hint[1] %> <%= resource.send attr_hint[0] %>
	  <% end %>
	</div>
	<% end %>
</div>

<div class="control_box">
<p><%= link_to 'Alterar', edit_resource_url(resource) %></p>
<p><%= link_to 'Remover', resource, :confirm => 'Tem certeza?', :method => :delete %></p>
<p><%= link_to 'Voltar', collection_url %></p>
</div>

<br class="clear" />

app/views/inherited_resources/_show_navigation.html.erb
<p><%= link_to "Edit", edit_resource_url(resource) %></p>
<p><%= link_to "Back", collection_url %></p>

app/views/inherited_resources/_system_sub_menu.erb
<div id="submenu">
	<ul>
		<li <% if controller_name=='users'%>class="active"<% end %>><%= link_to "usuários", users_path %></li>
		<li>produtos</li>
		<li>status de contrato</li>
	</ul>
</div>

app/views/inherited_resources/edit.html.erb
<h2>Alterar <%= resource.class.human_name.titleize %></h2>

<%= render "form" %>

<%= render "edit_navigation" %>

app/views/inherited_resources/index.html.erb
<%= render "index_navigation" %>


<% if collection.any? %>
  <%= render "collection_table" %>
<% end %>

app/views/inherited_resources/new.html.erb
<h2>Adicionar <%= resource.class.human_name.titleize %></h2>

<%= render "form" %>

<%= render "new_navigation" %>

app/views/inherited_resources/show.html.erb
<%= render "resource_detail" %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Haedron</title>
	<meta name="generator" content="TextMate http://macromates.com/">
	<meta name="author" content="Lucas Castro">
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
	<!-- Date: 2010-12-19 -->
</head>
<body>

<div id="wrap">
	
	<div id="top">
		
<h1 id="logo">Haedron</h1>
<hr />
<div id="user_nav">
	<% if user_signed_in? %>
		<p><%= current_user.email %> (<%= link_to "sair", destroy_user_session_path %>)</p>
	<% end %>
</div>
<div class="clear" id="menu">
	<ul>
		<li <% if controller_name=='accounts'%>class="active"<% end %>><%= link_to "contas", accounts_url %></li>
		<li<% if controller_name=='deals'%>class="active"<% end %> >contratos</li>
		<li <% if controller_name=='people'%>class="active"<% end %> >pessoas</li>
		<li <% if controller_name=='users' or controller_name=='system' %>class="active"<% end %> ><%= link_to "sistema", system_url %></li>
	</ul>
</div>
	</div>
	
<div id="content">	
    <%= yield %>		
</div>

<div id="footer">
	<a href="http://haedron.com.br">Haedron 2010</a>
</div>

</div>


</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Haedron</title>
	<meta name="generator" content="TextMate http://macromates.com/">
	<meta name="author" content="Lucas Castro">
  <%= stylesheet_link_tag "login" %>
  <%= csrf_meta_tag %>
	<!-- Date: 2010-12-19 -->
</head>
<body>

<div id="login">
<h1 id="logo">Haedron</h1>

<hr />
<%= yield %>		
</div>

</body>
</html>

app/views/system/index.html.erb
<%= render "system_sub_menu" %>

app/views/users/index.html.erb
<%= render "system_sub_menu" %>

<%= render "index_navigation" %>


<% if collection.any? %>
  <%= render "collection_table" %>
<% end %>